#!/usr/bin/perl

use strict;
use warnings;
# PODNAME: nopaste - command-line utility to nopaste

use App::Nopaste::Command;

if (my $url = App::Nopaste::Command->new_with_options->run) {
    print $url;
    print "\n";
}

__END__

=pod

=head1 DESCRIPTION

See the documentation of L<App::Nopaste::Command>.

=cut
